/**
 * Industry-specific persona templates
 * Pre-configured panel settings optimized for different industries
 */

import { PersonaConfig } from "./persona-generator";

export interface IndustryTemplate {
  id: string;
  name: string;
  description: string;
  industry: string;
  config: PersonaConfig;
}

export const INDUSTRY_TEMPLATES: IndustryTemplate[] = [
  {
    id: "technology-saas",
    name: "Technology / SaaS",
    description: "Tech-savvy professionals who evaluate and use software products",
    industry: "Technology",
    config: {
      demographics: {
        ageRange: { min: 22, max: 55 },
        genderDistribution: { male: 0.55, female: 0.43, nonBinary: 0.02 },
        locations: [
          "San Francisco, CA",
          "Seattle, WA",
          "Austin, TX",
          "New York, NY",
          "Boston, MA",
          "Denver, CO",
          "Los Angeles, CA",
          "Chicago, IL",
          "Portland, OR",
          "Remote",
        ],
        incomeDistribution: { low: 0.15, medium: 0.40, high: 0.45 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "Some college",
          "Doctoral degree",
        ],
        occupations: [
          "Software Engineer",
          "Product Manager",
          "UX Designer",
          "Data Scientist",
          "Engineering Manager",
          "DevOps Engineer",
          "Technical Lead",
          "Solutions Architect",
          "Startup Founder",
          "IT Manager",
          "Business Analyst",
          "QA Engineer",
        ],
      },
      psychographics: {
        values: [
          "Innovation",
          "Efficiency",
          "Career growth",
          "Work-life balance",
          "Continuous learning",
          "Problem-solving",
        ],
        lifestyles: [
          "Tech-savvy early adopter",
          "Busy professional",
          "Work-from-home",
          "Urban explorer",
          "Active and health-conscious",
        ],
        interests: [
          "Technology",
          "Programming",
          "Startups",
          "Productivity",
          "Gaming",
          "Science",
          "Podcasts",
          "Investing",
        ],
        personalities: [
          "Analytical and detail-oriented",
          "Creative and imaginative",
          "Ambitious and driven",
          "Organized and methodical",
          "Practical and grounded",
        ],
      },
      context: {
        industry: "Technology",
        productExperience: ["Daily user", "Regular user", "Evaluating", "New to product"],
        brandAffinities: ["Apple", "Google", "Microsoft", "Amazon", "Meta"],
      },
    },
  },
  {
    id: "healthcare",
    name: "Healthcare",
    description: "Healthcare professionals and patients with health-focused mindsets",
    industry: "Healthcare",
    config: {
      demographics: {
        ageRange: { min: 25, max: 65 },
        genderDistribution: { male: 0.40, female: 0.58, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Chicago, IL",
          "Houston, TX",
          "Philadelphia, PA",
          "Boston, MA",
          "San Diego, CA",
          "Dallas, TX",
          "Atlanta, GA",
          "Miami, FL",
        ],
        incomeDistribution: { low: 0.20, medium: 0.45, high: 0.35 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "Doctoral degree",
          "Associate degree",
          "Professional degree",
        ],
        occupations: [
          "Registered Nurse",
          "Physician",
          "Healthcare Administrator",
          "Physical Therapist",
          "Pharmacist",
          "Medical Technician",
          "Healthcare Consultant",
          "Nurse Practitioner",
          "Medical Researcher",
          "Health Insurance Professional",
        ],
      },
      psychographics: {
        values: [
          "Patient care",
          "Health and wellness",
          "Continuous learning",
          "Compassion",
          "Evidence-based practice",
          "Work-life balance",
        ],
        lifestyles: [
          "Active and health-conscious",
          "Busy professional",
          "Family-focused homebody",
          "Eco-conscious",
          "Work-from-home",
        ],
        interests: [
          "Health",
          "Medical research",
          "Fitness",
          "Nutrition",
          "Mental health",
          "Science",
          "Reading",
          "Volunteering",
        ],
        personalities: [
          "Analytical and detail-oriented",
          "Practical and grounded",
          "Organized and methodical",
          "Cautious and risk-averse",
          "Optimistic and enthusiastic",
        ],
      },
      context: {
        industry: "Healthcare",
        productExperience: ["Daily user", "Regular user", "Occasional user", "New to product"],
        brandAffinities: ["CVS", "Walgreens", "Kaiser", "UnitedHealth", "Mayo Clinic"],
      },
    },
  },
  {
    id: "finance-banking",
    name: "Finance / Banking",
    description: "Finance professionals and consumers interested in financial products",
    industry: "Finance",
    config: {
      demographics: {
        ageRange: { min: 25, max: 60 },
        genderDistribution: { male: 0.52, female: 0.46, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Chicago, IL",
          "Charlotte, NC",
          "San Francisco, CA",
          "Boston, MA",
          "Los Angeles, CA",
          "Dallas, TX",
          "Houston, TX",
          "Atlanta, GA",
          "Philadelphia, PA",
        ],
        incomeDistribution: { low: 0.10, medium: 0.35, high: 0.55 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "MBA",
          "Professional certification (CFA, CPA)",
        ],
        occupations: [
          "Financial Analyst",
          "Investment Banker",
          "Accountant",
          "Financial Advisor",
          "Portfolio Manager",
          "Risk Analyst",
          "Compliance Officer",
          "Bank Manager",
          "CFO",
          "Insurance Agent",
        ],
      },
      psychographics: {
        values: [
          "Financial security",
          "Career success",
          "Wealth building",
          "Risk management",
          "Analytical thinking",
          "Integrity",
        ],
        lifestyles: [
          "Busy professional",
          "Luxury-oriented",
          "Budget-conscious saver",
          "Urban explorer",
          "Family-focused homebody",
        ],
        interests: [
          "Finance",
          "Investing",
          "Real estate",
          "Economics",
          "Business news",
          "Golf",
          "Travel",
          "Wine",
        ],
        personalities: [
          "Analytical and detail-oriented",
          "Cautious and risk-averse",
          "Ambitious and driven",
          "Organized and methodical",
          "Practical and grounded",
        ],
      },
      context: {
        industry: "Finance",
        productExperience: ["Daily user", "Regular user", "Evaluating", "New to product"],
        brandAffinities: ["JPMorgan Chase", "Goldman Sachs", "Fidelity", "Vanguard", "American Express"],
      },
    },
  },
  {
    id: "ecommerce-retail",
    name: "E-commerce / Retail",
    description: "Online shoppers and retail enthusiasts across demographics",
    industry: "Retail",
    config: {
      demographics: {
        ageRange: { min: 18, max: 65 },
        genderDistribution: { male: 0.45, female: 0.53, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Chicago, IL",
          "Houston, TX",
          "Phoenix, AZ",
          "San Antonio, TX",
          "Dallas, TX",
          "San Diego, CA",
          "Austin, TX",
          "Miami, FL",
        ],
        incomeDistribution: { low: 0.30, medium: 0.45, high: 0.25 },
        educationLevels: [
          "High school diploma",
          "Some college",
          "Associate degree",
          "Bachelor's degree",
          "Master's degree",
        ],
        occupations: [
          "Retail Worker",
          "Manager",
          "Marketing Specialist",
          "Customer Service Representative",
          "Sales Representative",
          "E-commerce Specialist",
          "Store Manager",
          "Buyer",
          "Merchandiser",
          "Self-employed",
        ],
      },
      psychographics: {
        values: [
          "Value for money",
          "Convenience",
          "Quality",
          "Customer service",
          "Brand loyalty",
          "Sustainability",
        ],
        lifestyles: [
          "Budget-conscious saver",
          "Social butterfly",
          "Tech-savvy early adopter",
          "Family-focused homebody",
          "Luxury-oriented",
        ],
        interests: [
          "Shopping",
          "Fashion",
          "Technology",
          "Home decor",
          "Deals and coupons",
          "Product reviews",
          "Social media",
          "DIY projects",
        ],
        personalities: [
          "Spontaneous and adventurous",
          "Cautious and risk-averse",
          "Practical and grounded",
          "Outgoing and energetic",
          "Organized and methodical",
        ],
      },
      context: {
        industry: "Retail",
        productExperience: ["Frequent buyer", "Occasional buyer", "First-time buyer", "Browser"],
        brandAffinities: ["Amazon", "Target", "Walmart", "Costco", "Nike"],
      },
    },
  },
  {
    id: "education",
    name: "Education",
    description: "Educators, students, and lifelong learners",
    industry: "Education",
    config: {
      demographics: {
        ageRange: { min: 18, max: 65 },
        genderDistribution: { male: 0.38, female: 0.60, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Chicago, IL",
          "Houston, TX",
          "Boston, MA",
          "San Francisco, CA",
          "Seattle, WA",
          "Austin, TX",
          "Denver, CO",
          "Atlanta, GA",
        ],
        incomeDistribution: { low: 0.35, medium: 0.45, high: 0.20 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "Doctoral degree",
          "Some college",
          "Associate degree",
        ],
        occupations: [
          "Teacher",
          "Professor",
          "Student",
          "School Administrator",
          "Educational Consultant",
          "Librarian",
          "Tutor",
          "Curriculum Developer",
          "Researcher",
          "Teaching Assistant",
        ],
      },
      psychographics: {
        values: [
          "Education",
          "Personal growth",
          "Knowledge sharing",
          "Student success",
          "Innovation in learning",
          "Community",
        ],
        lifestyles: [
          "Busy professional",
          "Active and health-conscious",
          "Budget-conscious saver",
          "Family-focused homebody",
          "Eco-conscious",
        ],
        interests: [
          "Reading",
          "Education technology",
          "Research",
          "Writing",
          "Arts",
          "Science",
          "History",
          "Travel",
        ],
        personalities: [
          "Creative and imaginative",
          "Organized and methodical",
          "Outgoing and energetic",
          "Analytical and detail-oriented",
          "Optimistic and enthusiastic",
        ],
      },
      context: {
        industry: "Education",
        productExperience: ["Daily user", "Regular user", "Evaluating", "New to product"],
        brandAffinities: ["Pearson", "McGraw-Hill", "Coursera", "Khan Academy", "Google for Education"],
      },
    },
  },
  {
    id: "food-beverage",
    name: "Food & Beverage",
    description: "Food enthusiasts, restaurant-goers, and culinary professionals",
    industry: "Food & Beverage",
    config: {
      demographics: {
        ageRange: { min: 21, max: 65 },
        genderDistribution: { male: 0.48, female: 0.50, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Chicago, IL",
          "Houston, TX",
          "San Francisco, CA",
          "Miami, FL",
          "Seattle, WA",
          "Austin, TX",
          "Portland, OR",
          "New Orleans, LA",
        ],
        incomeDistribution: { low: 0.30, medium: 0.45, high: 0.25 },
        educationLevels: [
          "High school diploma",
          "Some college",
          "Associate degree",
          "Bachelor's degree",
          "Culinary degree",
        ],
        occupations: [
          "Chef",
          "Restaurant Manager",
          "Food Blogger",
          "Bartender",
          "Food Scientist",
          "Restaurant Owner",
          "Server",
          "Food Critic",
          "Caterer",
          "Home cook",
        ],
      },
      psychographics: {
        values: [
          "Quality food",
          "Culinary experiences",
          "Health and nutrition",
          "Sustainability",
          "Social dining",
          "Cultural exploration",
        ],
        lifestyles: [
          "Active and health-conscious",
          "Social butterfly",
          "Eco-conscious",
          "Urban explorer",
          "Luxury-oriented",
        ],
        interests: [
          "Cooking",
          "Food",
          "Wine",
          "Restaurants",
          "Travel",
          "Culture",
          "Health",
          "Sustainability",
        ],
        personalities: [
          "Creative and imaginative",
          "Outgoing and energetic",
          "Spontaneous and adventurous",
          "Practical and grounded",
          "Optimistic and enthusiastic",
        ],
      },
      context: {
        industry: "Food & Beverage",
        productExperience: ["Daily consumer", "Regular consumer", "Occasional consumer", "First-time buyer"],
        brandAffinities: ["Whole Foods", "Trader Joe's", "Starbucks", "Chipotle", "Blue Apron"],
      },
    },
  },
  {
    id: "automotive",
    name: "Automotive",
    description: "Car enthusiasts, commuters, and automotive professionals",
    industry: "Automotive",
    config: {
      demographics: {
        ageRange: { min: 25, max: 65 },
        genderDistribution: { male: 0.58, female: 0.40, nonBinary: 0.02 },
        locations: [
          "Detroit, MI",
          "Los Angeles, CA",
          "Houston, TX",
          "Dallas, TX",
          "Chicago, IL",
          "Atlanta, GA",
          "Phoenix, AZ",
          "San Diego, CA",
          "Denver, CO",
          "Charlotte, NC",
        ],
        incomeDistribution: { low: 0.20, medium: 0.45, high: 0.35 },
        educationLevels: [
          "High school diploma",
          "Some college",
          "Associate degree",
          "Bachelor's degree",
          "Technical certification",
        ],
        occupations: [
          "Automotive Engineer",
          "Car Salesperson",
          "Mechanic",
          "Fleet Manager",
          "Auto Journalist",
          "Transportation Manager",
          "Truck Driver",
          "Auto Body Technician",
          "Logistics Coordinator",
          "Car Designer",
        ],
      },
      psychographics: {
        values: [
          "Reliability",
          "Performance",
          "Safety",
          "Innovation",
          "Value for money",
          "Environmental impact",
        ],
        lifestyles: [
          "Busy professional",
          "Outdoor enthusiast",
          "Tech-savvy early adopter",
          "Family-focused homebody",
          "Luxury-oriented",
        ],
        interests: [
          "Cars",
          "Technology",
          "Sports",
          "DIY projects",
          "Travel",
          "Racing",
          "Electric vehicles",
          "Sustainability",
        ],
        personalities: [
          "Practical and grounded",
          "Analytical and detail-oriented",
          "Spontaneous and adventurous",
          "Cautious and risk-averse",
          "Ambitious and driven",
        ],
      },
      context: {
        industry: "Automotive",
        productExperience: ["Current owner", "Considering purchase", "Recent buyer", "Service customer"],
        brandAffinities: ["Toyota", "Ford", "Tesla", "Honda", "BMW"],
      },
    },
  },
  {
    id: "travel-hospitality",
    name: "Travel & Hospitality",
    description: "Travelers, hospitality workers, and adventure seekers",
    industry: "Travel & Hospitality",
    config: {
      demographics: {
        ageRange: { min: 21, max: 65 },
        genderDistribution: { male: 0.48, female: 0.50, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Miami, FL",
          "Las Vegas, NV",
          "Orlando, FL",
          "San Francisco, CA",
          "Chicago, IL",
          "Honolulu, HI",
          "Seattle, WA",
          "Denver, CO",
        ],
        incomeDistribution: { low: 0.25, medium: 0.40, high: 0.35 },
        educationLevels: [
          "High school diploma",
          "Some college",
          "Associate degree",
          "Bachelor's degree",
          "Master's degree",
        ],
        occupations: [
          "Hotel Manager",
          "Travel Agent",
          "Flight Attendant",
          "Tour Guide",
          "Restaurant Manager",
          "Concierge",
          "Event Planner",
          "Travel Blogger",
          "Pilot",
          "Hospitality Consultant",
        ],
      },
      psychographics: {
        values: [
          "Adventure",
          "Cultural experiences",
          "Relaxation",
          "Quality service",
          "Convenience",
          "Value for money",
        ],
        lifestyles: [
          "Outdoor enthusiast",
          "Social butterfly",
          "Spontaneous and adventurous",
          "Luxury-oriented",
          "Urban explorer",
        ],
        interests: [
          "Travel",
          "Adventure",
          "Culture",
          "Photography",
          "Food",
          "Nature",
          "History",
          "Languages",
        ],
        personalities: [
          "Spontaneous and adventurous",
          "Outgoing and energetic",
          "Optimistic and enthusiastic",
          "Flexible and adaptable",
          "Creative and imaginative",
        ],
      },
      context: {
        industry: "Travel & Hospitality",
        productExperience: ["Frequent traveler", "Occasional traveler", "First-time traveler", "Business traveler"],
        brandAffinities: ["Marriott", "Airbnb", "Delta", "Expedia", "Hilton"],
      },
    },
  },
  {
    id: "real-estate",
    name: "Real Estate",
    description: "Homebuyers, renters, and real estate professionals",
    industry: "Real Estate",
    config: {
      demographics: {
        ageRange: { min: 25, max: 70 },
        genderDistribution: { male: 0.48, female: 0.50, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "Los Angeles, CA",
          "Miami, FL",
          "San Francisco, CA",
          "Chicago, IL",
          "Dallas, TX",
          "Seattle, WA",
          "Phoenix, AZ",
          "Denver, CO",
          "Austin, TX",
        ],
        incomeDistribution: { low: 0.20, medium: 0.40, high: 0.40 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "Some college",
          "Associate degree",
          "High school diploma",
        ],
        occupations: [
          "Real Estate Agent",
          "Property Manager",
          "Mortgage Broker",
          "Home Inspector",
          "Real Estate Investor",
          "Appraiser",
          "Real Estate Attorney",
          "Construction Manager",
          "Interior Designer",
          "Home buyer",
        ],
      },
      psychographics: {
        values: [
          "Financial security",
          "Homeownership",
          "Investment",
          "Location",
          "Quality of life",
          "Family",
        ],
        lifestyles: [
          "Family-focused homebody",
          "Suburban comfort seeker",
          "Urban explorer",
          "Busy professional",
          "Luxury-oriented",
        ],
        interests: [
          "Real estate",
          "Home improvement",
          "Interior design",
          "Finance",
          "Gardening",
          "Architecture",
          "Investing",
          "DIY projects",
        ],
        personalities: [
          "Practical and grounded",
          "Analytical and detail-oriented",
          "Cautious and risk-averse",
          "Ambitious and driven",
          "Organized and methodical",
        ],
      },
      context: {
        industry: "Real Estate",
        productExperience: ["First-time buyer", "Repeat buyer", "Renter", "Investor"],
        brandAffinities: ["Zillow", "Redfin", "Realtor.com", "Coldwell Banker", "RE/MAX"],
      },
    },
  },
  {
    id: "b2b-services",
    name: "B2B Services",
    description: "Business professionals and decision-makers in B2B contexts",
    industry: "Professional Services",
    config: {
      demographics: {
        ageRange: { min: 28, max: 60 },
        genderDistribution: { male: 0.52, female: 0.46, nonBinary: 0.02 },
        locations: [
          "New York, NY",
          "San Francisco, CA",
          "Chicago, IL",
          "Los Angeles, CA",
          "Boston, MA",
          "Seattle, WA",
          "Dallas, TX",
          "Atlanta, GA",
          "Denver, CO",
          "Washington, DC",
        ],
        incomeDistribution: { low: 0.10, medium: 0.35, high: 0.55 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "MBA",
          "Doctoral degree",
        ],
        occupations: [
          "CEO",
          "CTO",
          "VP of Operations",
          "Director of Marketing",
          "Procurement Manager",
          "Business Development Manager",
          "Consultant",
          "Account Executive",
          "Operations Manager",
          "IT Director",
        ],
      },
      psychographics: {
        values: [
          "ROI",
          "Efficiency",
          "Reliability",
          "Partnership",
          "Innovation",
          "Scalability",
        ],
        lifestyles: [
          "Busy professional",
          "Work-from-home",
          "Tech-savvy early adopter",
          "Luxury-oriented",
          "Active and health-conscious",
        ],
        interests: [
          "Business strategy",
          "Technology",
          "Leadership",
          "Industry trends",
          "Networking",
          "Golf",
          "Investing",
          "Travel",
        ],
        personalities: [
          "Analytical and detail-oriented",
          "Ambitious and driven",
          "Organized and methodical",
          "Practical and grounded",
          "Cautious and risk-averse",
        ],
      },
      context: {
        industry: "Professional Services",
        productExperience: ["Decision maker", "Influencer", "End user", "Evaluating"],
        brandAffinities: ["Salesforce", "Microsoft", "SAP", "Oracle", "IBM"],
      },
    },
  },
  {
    id: "entertainment-media",
    name: "Entertainment / Media",
    description: "Content creators, media consumers, and entertainment enthusiasts",
    industry: "Entertainment",
    config: {
      demographics: {
        ageRange: { min: 18, max: 55 },
        genderDistribution: { male: 0.48, female: 0.50, nonBinary: 0.02 },
        locations: [
          "Los Angeles, CA",
          "New York, NY",
          "Atlanta, GA",
          "Nashville, TN",
          "Miami, FL",
          "Chicago, IL",
          "Austin, TX",
          "San Francisco, CA",
          "Seattle, WA",
          "Denver, CO",
        ],
        incomeDistribution: { low: 0.35, medium: 0.40, high: 0.25 },
        educationLevels: [
          "High school diploma",
          "Some college",
          "Bachelor's degree",
          "Associate degree",
          "Master's degree",
        ],
        occupations: [
          "Content Creator",
          "Video Producer",
          "Musician",
          "Actor",
          "Journalist",
          "Social Media Manager",
          "Graphic Designer",
          "Film Director",
          "Podcast Host",
          "Gamer/Streamer",
        ],
      },
      psychographics: {
        values: [
          "Creativity",
          "Self-expression",
          "Entertainment",
          "Authenticity",
          "Community",
          "Innovation",
        ],
        lifestyles: [
          "Social butterfly",
          "Tech-savvy early adopter",
          "Urban explorer",
          "Creative professional",
          "Night owl",
        ],
        interests: [
          "Movies",
          "Music",
          "Gaming",
          "Social media",
          "Podcasts",
          "Art",
          "Fashion",
          "Technology",
        ],
        personalities: [
          "Creative and imaginative",
          "Outgoing and energetic",
          "Spontaneous and adventurous",
          "Optimistic and enthusiastic",
          "Flexible and adaptable",
        ],
      },
      context: {
        industry: "Entertainment",
        productExperience: ["Daily user", "Regular user", "Occasional user", "New user"],
        brandAffinities: ["Netflix", "Spotify", "YouTube", "Disney", "TikTok"],
      },
    },
  },
  {
    id: "nonprofit",
    name: "Non-profit",
    description: "Social impact workers, donors, and community advocates",
    industry: "Non-profit",
    config: {
      demographics: {
        ageRange: { min: 22, max: 70 },
        genderDistribution: { male: 0.40, female: 0.58, nonBinary: 0.02 },
        locations: [
          "Washington, DC",
          "New York, NY",
          "San Francisco, CA",
          "Chicago, IL",
          "Los Angeles, CA",
          "Boston, MA",
          "Seattle, WA",
          "Denver, CO",
          "Atlanta, GA",
          "Portland, OR",
        ],
        incomeDistribution: { low: 0.35, medium: 0.45, high: 0.20 },
        educationLevels: [
          "Bachelor's degree",
          "Master's degree",
          "Doctoral degree",
          "Some college",
        ],
        occupations: [
          "Executive Director",
          "Program Manager",
          "Fundraiser",
          "Grant Writer",
          "Volunteer Coordinator",
          "Social Worker",
          "Community Organizer",
          "Policy Analyst",
          "Communications Manager",
          "Board Member",
        ],
      },
      psychographics: {
        values: [
          "Social impact",
          "Community",
          "Compassion",
          "Justice",
          "Sustainability",
          "Service",
        ],
        lifestyles: [
          "Eco-conscious",
          "Active and health-conscious",
          "Family-focused homebody",
          "Budget-conscious saver",
          "Urban explorer",
        ],
        interests: [
          "Social causes",
          "Volunteering",
          "Politics",
          "Environment",
          "Education",
          "Health",
          "Community",
          "Reading",
        ],
        personalities: [
          "Optimistic and enthusiastic",
          "Creative and imaginative",
          "Organized and methodical",
          "Outgoing and energetic",
          "Practical and grounded",
        ],
      },
      context: {
        industry: "Non-profit",
        productExperience: ["Active donor", "Volunteer", "Staff member", "Supporter"],
        brandAffinities: ["United Way", "Red Cross", "Habitat for Humanity", "UNICEF", "Local charities"],
      },
    },
  },
];

export function getIndustryTemplate(id: string): IndustryTemplate | undefined {
  return INDUSTRY_TEMPLATES.find((t) => t.id === id);
}

export function getTemplatesByIndustry(industry: string): IndustryTemplate[] {
  return INDUSTRY_TEMPLATES.filter((t) => t.industry === industry);
}
